[project]
name = "boreas-dataplattform"
version = "0.1.0"
description = "The dataplatform for the avalanche dataplatform Boreas"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alive-progress>=2.3.1",
    "dbt-core>=1.11.2",
    "dbt-duckdb>=1.10.0",
    "dlt[duckdb,workspace]>=1.20.0",
    "duckdb>=1.4.3",
    "enlighten>=1.14.1",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
    "dagster>=1.11",
    "dagster-webserver>=1.11",
    "dagster-dbt>=0.27",
    "dagster-dlt>=0.27",
    "dagster-duckdb>=0.27",
    "dagster-dg-cli>=1.13.14",
    "elementary-data[duckdb]>=0.19.0",
]

[tool.dagster]
module_name = "src.dagster_boreas.definitions"
code_location_name = "boreas"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_boreas"
code_location_target_module = "src.dagster_boreas.definitions"
code_location_name = "boreas"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "dagster_boreas*", "dlt_boreas*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
