select
    date::date as date,
    max_temp,
    average_temperature,
    min_temp,
    max_relative_humidity,
    average_relative_humidity,
    min_relative_humidity,
    max_snowfall,
    average_snowfall,
    min_snowfall,
    max_rain,
    average_rain,
    min_rain,
    max_snow_depth,
    average_snow_depth,
    min_snow_depth,
    max_windspeed,
    average_windspeed,
    min_windspeed,
    weather_type,
    east_south_lon,
    east_south_lat,
    west_north_lon,
    west_north_lat,
    (east_south_lat + west_north_lat) / 2.0 as center_lat,
    (east_south_lon + west_north_lon) / 2.0 as center_lon
from "3_gold"."weather_per_region"
where date is not null
