name: Deploy Streamlit to Azure

on:
  push:
    branches: [main]
    paths:
      - 'dashboard/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          file: ./Dockerfile
      
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-boreas-prod
          images: ghcr.io/${{ github.repository }}:latest
          slot-name: production
      
      - name: Azure Logout
        run: az logout
