version: 2

sources:
  - name: 1_bronze
    schema: 1_bronze
    tables:
      - name: weather_forecast
      - name: weather_historic
      - name: avalanche_regions
      - name: avalanche_danger_levels
