version: 2

models:
  - name: avalanche_per_region
    tests:
      - elementary.volume_anomalies:
          time_bucket: {period: day, count: 1}
          timestamp_column: valid_from
      - elementary.dimension_anomalies:
          timestamp_column: valid_from
          dimensions: [region_id]
      - elementary.dimension_anomalies:
          timestamp_column: valid_from
          dimensions: [danger_level]
      - elementary.all_columns_anomalies:
          timestamp_column: valid_from
          column_anomalies: [null_count, zero_count, min, max, average, standard_deviation]
          dimensions: [region_id]

  - name: weather_per_region
    tests:
      - elementary.volume_anomalies:
          time_bucket: {period: day, count: 1}
          timestamp_column: date
      - elementary.dimension_anomalies:
          timestamp_column: date
          dimensions: [weather_type]
